// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWS0ds1TPcvfJqZDvFHmpqkXquzne8pjU',
    appId: '1:189839201542:web:80492ebb39d98ed64f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    authDomain: 'semsdevop.firebaseapp.com',
    storageBucket: 'semsdevop.appspot.com',
    measurementId: 'G-75FET2GNGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiKA9JCjqxFifGAyrclNtOW0sEM-9CYgM',
    appId: '1:189839201542:android:52c98ec1ca9d8fc74f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    storageBucket: 'semsdevop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEYeFOpfZu4gtEnpUnVHAmWLUe0kxYGA',
    appId: '1:189839201542:ios:476981f87138b7734f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    storageBucket: 'semsdevop.appspot.com',
    iosBundleId: 'com.example.sems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEEYeFOpfZu4gtEnpUnVHAmWLUe0kxYGA',
    appId: '1:189839201542:ios:476981f87138b7734f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    storageBucket: 'semsdevop.appspot.com',
    iosBundleId: 'com.example.sems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWS0ds1TPcvfJqZDvFHmpqkXquzne8pjU',
    appId: '1:189839201542:web:e910db91bcee62784f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    authDomain: 'semsdevop.firebaseapp.com',
    storageBucket: 'semsdevop.appspot.com',
    measurementId: 'G-7NV7QEDH7K',
  );
}
